export default [
  {
    id: 0,
    title: 'trainers',
    description: 'Trainers In White',
    price: 76,
    favourite: true,
    label: false,
  },
  {
    id: 1,
    title: 'boots',
    description: 'Trainers In Blue',
    price: {
      old: 56,
      new: 45,
      percents: 20,
    },
    favourite: false,
    label: 'Sale',
  },
  {
    id: 2,
    title: 'flat sandals',
    description: 'Trainers In White',
    price: 55,
    favourite: false,
    label: 'New',
  },
  {
    id: 3,
    title: 'trainers',
    description: 'Trainers In White',
    price: 76,
    favourite: true,
    label: false,
  },
  {
    id: 4,
    title: 'boots',
    description: 'Trainers In Blue',
    price: {
      old: 56,
      new: 45,
      percents: 20,
    },
    favourite: false,
    label: 'Sale',
  },
  {
    id: 5,
    title: 'flat sandals',
    description: 'Trainers In White',
    price: 55,
    favourite: false,
    label: 'New',
  },
];
