// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//   aws_project_region: 'us-west-2',
//   aws_appsync_graphqlEndpoint: 'https://t4g4rmdnzrdavj55j75spy3ig4.appsync-api.us-west-2.amazonaws.com/graphql',
//   aws_appsync_region: 'us-west-2',
//   aws_appsync_authenticationType: 'API_KEY',
//   aws_appsync_apiKey: 'da2-ajwj5ldfkvgvrmo2trcfci2v2u',
// };

// export default awsmobile;

// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_appsync_graphqlEndpoint:
		'https://6krcbmdl3jcqjbr4vg6zjhe334.appsync-api.us-east-2.amazonaws.com/graphql',
	aws_appsync_region: 'us-east-2',
	aws_appsync_authenticationType: 'API_KEY',
	aws_appsync_apiKey: 'da2-p5xs6qfaqrdwxojrxj52yhh4ge'
};

export default awsmobile;
