query listVisitTables {
	listVisitTables {
		items {
			id
			salesMan
			client
			binnacle
			visitDate
			visitEndDate
			visitStateId
			visitSate
			visitStartAddress
			visitClientAddress
			visitDuration
		}
	}
}
