query listVisits {
  listVisits {
    items {
      id
      salesmanId
      salesmanName
      clientId
      clientName
      visitDate
      visitEndDate
      visitStateId
      visitState
      visitstartAddress
      visitclientAddress
      visitduration
    }
  }
}
